### ISSUE TITLE
Segmentation Fault ./mineserver

### ISSUE THREAD

**Issue by timatooth** [Mineserver/mineserver2#5]
Not sure if this information is useful but I thought I'd help with the bug fixing for Mac builds. 

Seems like libiconv is having trouble encoding the motd & playercount to send or something because the program crashed as soon as the client 'polls'

-libiconv-1.14
-boost 1.48

**_Compiling boost initial output iconv pops up there**_

Performing configuration checks
    - has_icu builds           : no
warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam
    - iconv (libc)             : no
    - iconv (separate)         : yes
    - icu                      : no
    - icu (lib64)              : no
    - ../config//has_gcc_visibility builds : yes
    - ../config//has_long_double_support builds : yes
warning: skipping optional Message Passing Interface (MPI) library.
note: to enable MPI support, add "using mpi ;" to user-config.jam.
note: to suppress this message, pass "--without-mpi" to bjam.
note: otherwise, you can safely ignore this message.

My macs library setup might be the root cause of this.

timsullivan@tim-mac:~/src/mineserver2/bin$ ./mineserver
Got bytes: fe
Found packet: fe
State is: 0
State is: 1
There are 1 messages.
Server list ping watcher called!
Watchers done.
Trying to send message ID: ff
Segmentation fault

Using Wireshark, no response is heard.
00000000  fe                                               .

timsullivan@tim-mac:~/src/mineserver2/bin$ gdb ./mineserver
GNU gdb 6.3.50-20050815 (Apple version gdb-1515) (Sat Jan 15 08:33:48 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries ......... done

(gdb) rn
Undefined command: "rn".  Try "help".
(gdb) run
Starting program: /Users/timsullivan/src/mineserver2/bin/mineserver 
Reading symbols for shared libraries .++++++++ done
Got bytes: fe
Found packet: fe
State is: 0
State is: 1
There are 1 messages.
Server list ping watcher called!
Watchers done.
Trying to send message ID: ff

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0xffffffffffffffff
0x000000010035195e in libiconv (icd=0xffffffffffffffff, inbuf=0x7fff5fbff0e8, inbytesleft=0x7fff5fbff100, outbuf=0x7fff5fbff110, outbytesleft=0x7fff5fbff0f0) at ./iconv.c:254
254     return cd->lfuncs.loop_convert(icd,
(gdb) back
#0  0x000000010035195e in libiconv (icd=0xffffffffffffffff, inbuf=0x7fff5fbff0e8, inbytesleft=0x7fff5fbff100, outbuf=0x7fff5fbff110, outbytesleft=0x7fff5fbff0f0) at ./iconv.c:254
#1  0x000000010003c913 in Mineserver::Network_Protocol_Notch_PacketStream::operator<< (this=0x100516598, str=@0x100517068) at /Users/timsullivan/src/mineserver2/src/mineserver/network/protocol/notch/packetstream.cpp:358
#2  0x000000010004a1c6 in Mineserver::Network_Protocol_Notch_Packet_0xFF::_write (this=0x7fff5fbff1d0, ps=@0x100516598, message=@0x100517060) at /Users/timsullivan/src/mineserver2/src/mineserver/network/protocol/notch/packet/0xFF.cpp:47
#3  0x000000010003b2ca in Mineserver::Network_Protocol_Notch_Packet::write (this=0x7fff5fbff1d0, ps=@0x100516598, message=@0x100517060) at packet.h:53
#4  0x000000010003a1c2 in Mineserver::Network_Protocol_Notch_Protocol::compose (this=0x100516590, bytes=@0x1005170d0, message=@0x100517060) at /Users/timsullivan/src/mineserver2/src/mineserver/network/protocol/notch/protocol.cpp:903
#5  0x0000000100035795 in Mineserver::Network_Client::write (this=0x100802c20) at /Users/timsullivan/src/mineserver2/src/mineserver/network/client.cpp:115
#6  0x00000001000296b1 in Mineserver::Game::run (this=0x100801220) at /Users/timsullivan/src/mineserver2/src/mineserver/game.cpp:87
#7  0x0000000100008a26 in main () at /Users/timsullivan/src/mineserver2/src/app.cpp:69

Current language:  auto; currently c

**Comment by timatooth** [comment]
I have now fixed this issue. The libiconv (v1.14) I build from source was defective. There is no problem with the one that already bundles with mac os. Now that CMake can find it!
